### PR TITLE
Add staff authentication

### PR DESCRIPTION
**Pull request by csc530**
add login (authentication) and authorization for database access and changes

### CODE REVIEW

**Comment by csc530** [comment]
currently using the existing Microsoft Entra ID (ANSS org. emails) as an external identity provider for Fauna is not possible because the `aud` claim within the ID tokens can't be edited to Fauna's audience.

follow below forums for answers...if any.
- https://learn.microsoft.com/en-us/answers/questions/1842462/how-to-add-an-aud-claim-to-jwt-id-token?page=1&orderby=Helpful&comment=answer-1622464#newest-answer-comment
- https://stackoverflow.com/questions/78790257/how-to-add-an-aud-claim-to-a-microsoft-entra-id-jwt
- https://forums.fauna.com/t/how-to-use-microsoft-entra-id-as-an-access-provider/4009

**Comment by theahmadzai** [comment]
Awesome work @csc530, I did not get what you're doing with the JWT tokens but since you're driving the project now if you would like to choose another database or anything feel free to do so, also let me know if you need access to fauna or netlify credentials, also I have made you collaborator in the project, let me know if you need any additional access.

**Comment by csc530** [comment]
thx, essentially Fauna needs a customized JWT from Microsoft which they don't allow (at least from what I saw)

The only db I'd suggest switching to is Azure SQL DB or Cosmos then everything is integrated and no need for extra authentication or permission management. I'm waiting for Samandar's feedback, and hopefully, they can activate their Azure subscription soon.

**Comment by csc530** [comment]
@theahmadzai, @sami-mahmodi I'm going to merge my 2 pull requests are there any additional checks or guidelines I should follow, look, or review for before I continue (for now and in the future)?

**Comment by theahmadzai** [comment]
You can merge your changes since it does not affect any existing features, you're doing good your code is clean and readable.

**Pull request merged**
